export const _router = {
	auth: { index: "/auth", login: "/auth/login", forgotpassword: "/auth/forgot-password", resetpassword: "/auth/reset-password" },
	dashboard: {
		index: "/dashboard",
		notifications: "/dashboard/notifications",
		customers: "/dashboard/customers",
		selectCustomerPaymentMethod: "/dashboard/customers/payment-method",
		customerAdd: "/dashboard/customers/add",
		customerDetails: "/dashboard/customers/:id",
		customerDetailsReceipt: "/dashboard/customers/:id/receipt",
		properties: "/dashboard/properties",
		propertiesDetails: "/dashboard/properties/:id",
		addProperties: "/dashboard/properties/add",
		categories: "/dashboard/properties/categories",
		manageCategories: "/dashboard/properties/manage-categories",
		receipt: "/dashboard/receipt",
		receiptDetails: "/dashboard/receipt/:id",
		settings: "/dashboard/settings",
		contract: "/dashboard/contract",
		contractDetails: "/dashboard/contract/:id",
		contractReceipt: "/dashboard/contract/:id/receipt",
		productRequest: "/dashboard/product-request",
		productRequestDetails: "/dashboard/product-request/:id",
		debt: "/dashboard/debt",
		debtDetails: "/dashboard/debt/:id",
		payment: "/dashboard/payment",
		reportAnalytics: "/dashboard/report-analytics",
		auditAndCompliance: "/dashboard/audit-and-compliance",
		users: "/dashboard/users",
		addUser: "/dashboard/users/add",
		userDetails: "/dashboard/users/:id",
	},
};
