export const API_ROUTES = {
	auth: {
		login: "/auth/login",
		refreshToken: "/auth/refresh-token",
		logout: "/auth/logout",
	},
	user: {
		createUser: "/user/create",
		getAllUsers: "/user",
		getUserById: (id: string) => `/user/${id}`,
		updateUser: (id: string) => `/user/update/${id}`,
		resetPassword: (id: string) => `/user/reset-password/${id}`,
		changePassword: "/user/change-password",
		suspendUser: (id: string) => `/user/suspend/${id}`,
		uploadUserProfile: (id: string) => `/user/upload/${id}`,
		deleteUser: (id: string) => `/user/delete/${id}`,
	},
	media: {
		getPresignedUploadUrl: "/media/presign-upload",
		getPresignedUrlByKey: "/media/get-url-by-key",
	},
	loginHistory: {
		getLoginHistory: "/login-history",
		getUserLoginHistory: (userId: string) => `/login-history/user/${userId}`,
	},
	reference: {
		getAllReferenceData: "/reference",
		getReferenceDataByType: (type: string) => `/reference/${type}`,
	},
	property: {
		createProperty: "/property",
		getAllProperties: "/property",
		getPropertyById: (id: string) => `/property/${id}`,
		updateProperty: (id: string) => `/property/${id}`,
		deleteProperty: (id: string) => `/property/${id}`,
	},
	auditLogs: {
		getAuditLogs: "/audit-logs",
		getAuditLogsGrouped: "/audit-logs/grouped",
	},
	customer: {
		getAllCustomers: "/customer",
		getCustomerDetails: (customerId: string) => `/customer/${customerId}`,
		updateCustomer: (customerId: string) => `/customer/${customerId}`,
		deleteCustomer: (customerId: string) => `/customer/${customerId}`,
		getApprovedRegistrations: (customerId: string) => `/customer/approved-registrations/${customerId}`,
		getRegistrationsByEmail: (email: string) => `/customer/registrations/${email}`,
		getCustomerContracts: (customerId: string) => `/customer/${customerId}/contracts`,
		getCustomerPayments: (customerId: string) => `/customer/payments/${customerId}`,
		getCustomerDocuments: (customerId: string) => `/customer/documents/${customerId}`,
		getCustomerReceipts: (customerId: string) => `/customer/receipts/${customerId}`,
		sendEmailSpecific: "/customer/send-email/specific",
		sendEmailBroadcast: "/customer/send-email/broadcast",
	},
	customerRegistration: {
		createExternalCustomerRegistration: "/customer-registration",
		getExternalCustomerRegistrations: "/customer-registration/external",
		getAllCustomerRegistrations: "/customer-registration",
		createInternalCustomerRegistration: "/customer-registration/internal",
		createFullPaymentRegistration: "/customer-registration/full-payment",
		createInternalFullPaymentRegistration: "/customer-registration/full-payment/internal",
		approveCustomerRegistration: (registrationId: string) => `/customer-registration/approve/${registrationId}`,
		getCustomerRegistrationById: (registrationId: string) => `/customer-registration/${registrationId}`,
		updateCustomerRegistration: (id: string) => `/customer-registration/${id}`,
		declineCustomerRegistration: (id: string) => `/customer-registration/${id}/decline`,
	},
	contractDocument: {
		send: "/contract-document/send",
	},
	notifications: {
		getNotifications: "/notifications",
		getUnreadNotificationCount: "/notifications/unread-count",
		markAllNotificationsRead: "/notifications/mark-all-read",
	},
	contracts: {
		createContract: "/contracts/create",
		getContractPayments: (id: string) => `/contracts/${id}/payments`,
		getSignedContract: (id: string) => `/contracts/${id}/signed-contract`,
		getAllContracts: "/contracts",
		getAllContractDebts: "/contracts/debts",
		getContractHistory: (id: string) => `/contracts/${id}`,
		getContractDebtDetails: (id: string) => `/contracts/debt/${id}`,
		terminateContract: (id: string) => `/contracts/terminate/${id}`,
		pauseContract: (id: string) => `/contracts/pause/${id}`,
		resumeContract: (id: string) => `/contracts/resume/${id}`,
	},
	paymentSchedule: {
		generatePaymentLink: (scheduleId: string) => `/payment-schedule/generate-link/${scheduleId}`,
		getPaymentSchedules: (id: string) => `/payment-schedule/${id}`,
		getNextPayment: (id: string) => `/payment-schedule/next-payment/${id}`,
	},
	payment: {
		getPendingPayments: "/payment/pending",
		getFailedPayments: "/payment/failed",
		verifyPayment: (reference: string) => `/payment/verify/${reference}`,
		getAllPayments: "/payment/all",
	},
	receipt: {
		getAllReceipts: "/receipt",
		getReceiptsById: (id: string) => `/receipt/${id}`,
	},
	analytics: {
		getAnalyticsOverview: "/analytics",
		getIncomeAnalytics: "/analytics/income",
		getRevenueAnalytics: "/analytics/revenue",
	},
	reports: {
		getVATRecordsList: "/reports",
		getIncomeEarned: (period: string) => `/reports/income-earned/${period}`,
		getVatCollected: (period: string) => `/reports/vat-collected/${period}`,
		getInterestPenalties: (period: string) => `/reports/interest-penalties/${period}`,
		getPenalties: "/reports/penalties",
	},
	duePayment: {
		getAllDuePayments: "/due-payments",
	},
	settings: {
		getSystemSettings: "/settings",
		updateVATRate: "/settings/vat",
		updateInterestRate: "/settings/interest",
		updatePenaltyInterestRate: "/settings/penalty-interest",
	},
	generateReceipt: "/generate-receipt",
	getNextScheduleForReceipt: (contractId: string) => `/generate-receipt/schedules/${contractId}`,
	propertyCategories: {
		createCategory: "/categories",
		getAllCategories: "/categories",
		addSubcategory: (id: string) => `/categories/${id}/subcategories`,
		getAllCategoriesFlat: "/categories/flat",
		getCategoryById: (id: string) => `/categories/${id}`,
		updateCategory: (id: string) => `/categories/${id}`,
		deleteCategory: (id: string) => `/categories/${id}`,
		deleteSubcategory: (subcategoryId: string) => `/categories/subcategories/${subcategoryId}`,
	},
} as const;
