import React from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogClose } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import CustomInput from "@/components/base/CustomInput";
import { inputStyle, labelStyle, modalContentStyle, selectTriggerStyle } from "@/components/common/commonStyles";
import ActionButton from "@/components/base/ActionButton";
import { Textarea } from "@/components/ui/textarea";

export default function GenerateReceiptModal({ open, onOpenChange }: { open: boolean; onOpenChange: (o: boolean) => void }) {
	const [selectedCustomer, setSelectedCustomer] = React.useState<string | undefined>(undefined);

	const handleSubmit = (e: React.FormEvent) => {
		e.preventDefault();
		// TODO: generate receipt
		onOpenChange(false);
	};

	return (
		<Dialog open={open} onOpenChange={onOpenChange}>
			<DialogContent className={modalContentStyle("md:max-w-3xl")}>
				<DialogHeader className="justify-center flex flex-row mt-2 text-center">
					<DialogTitle>Generate Receipt</DialogTitle>
					<DialogClose />
				</DialogHeader>

				<form onSubmit={handleSubmit} className="grid max-w-2xl mx-auto items-end grid-cols-1 sm:grid-cols-2 gap-4 md:gap-x-8 md:gap-y-5 py-4 mt-4">
					<div>
						<Label className={labelStyle()}>Full name*</Label>
						<Select onValueChange={(v) => setSelectedCustomer(v)} value={selectedCustomer}>
							<SelectTrigger className={selectTriggerStyle()}>
								<SelectValue placeholder="Search customer" />
							</SelectTrigger>
							<SelectContent>
								<div className="p-1.5">
									<CustomInput placeholder="Search by name" className={inputStyle} />
								</div>
								<SelectItem value="tom">Tom Doe James</SelectItem>
								<SelectItem value="thomas">Thomas Doe James</SelectItem>
								<SelectItem value="ogun">Thomas James Ogun</SelectItem>
							</SelectContent>
						</Select>
					</div>

					<CustomInput label="Customer ID" required />

					<div>
						<Label className={labelStyle()}>Payment Method*</Label>
						<Select>
							<SelectTrigger className={selectTriggerStyle()}>
								<SelectValue placeholder="Select payment method" />
							</SelectTrigger>
							<SelectContent>
								<SelectItem value="paystack">Paystack</SelectItem>
								<SelectItem value="bank">Bank Transfer</SelectItem>
							</SelectContent>
						</Select>
					</div>
					<CustomInput label="Amount Paid" required />
					<CustomInput label="Payment Date" required />
					<CustomInput label="Generated By" required />
					<div className="col-span-2">
						<Label className={labelStyle()}>Note / Remark</Label>
						<Textarea className={inputStyle} rows={3} />
					</div>

					<DialogFooter className="col-span-2 mt-5">
						<ActionButton fullWidth className="py-3">
							Generate Receipt
						</ActionButton>
					</DialogFooter>
				</form>
			</DialogContent>
		</Dialog>
	);
}
