import React from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogClose } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import CustomInput from "@/components/base/CustomInput";
import { inputStyle, labelStyle, modalContentStyle, selectTriggerStyle } from "@/components/common/commonStyles";
import ActionButton from "@/components/base/ActionButton";
import { Textarea } from "@/components/ui/textarea";
import { useGetAllCustomers } from "@/api/customer";

export default function GenerateReceiptModal({ open, onOpenChange }: { open: boolean; onOpenChange: (o: boolean) => void }) {
	const [selectedCustomer, setSelectedCustomer] = React.useState<string | undefined>(undefined);
	const [customerSearch, setCustomerSearch] = React.useState("");
	const [currentPage, setCurrentPage] = React.useState(1);

	const { data: customersData, isLoading: customersLoading } = useGetAllCustomers(currentPage, 50, customerSearch, "name", "asc");

	const handleSubmit = (e: React.FormEvent) => {
		e.preventDefault();
		// TODO: generate receipt
		onOpenChange(false);
	};

	return (
		<Dialog open={open} onOpenChange={onOpenChange}>
			<DialogContent className={modalContentStyle("md:max-w-3xl")}>
				<DialogHeader className="justify-center flex flex-row mt-2 text-center">
					<DialogTitle>Generate Receipt</DialogTitle>
					<DialogClose />
				</DialogHeader>

				<form onSubmit={handleSubmit} className="grid max-w-2xl mx-auto items-end grid-cols-1 sm:grid-cols-2 gap-4 md:gap-x-8 md:gap-y-5 py-4 mt-4">
					<div>
						<Label className={labelStyle()}>Full name*</Label>
						<Select onValueChange={(v) => setSelectedCustomer(v)} value={selectedCustomer}>
							<SelectTrigger className={selectTriggerStyle()}>
								<SelectValue placeholder="Search customer" />
							</SelectTrigger>
							<SelectContent>
								<div className="p-1.5">
									<CustomInput
										placeholder="Search by name"
										className={inputStyle}
										value={customerSearch}
										onChange={(e) => {
											setCustomerSearch((e.target as HTMLInputElement).value);
											setCurrentPage(1); // Reset to first page on search
										}}
									/>
								</div>
								{customersLoading ? (
									<div className="p-2 text-center text-sm text-gray-500">Loading...</div>
								) : (
									<>
										{customersData?.data?.map((customer) => (
											<SelectItem key={customer.id} value={customer.id}>
												{customer.fullName}
											</SelectItem>
										)) || []}
										{customersData?.pagination && (
											<div className="flex items-center justify-between p-2 border-t">
												<button
													type="button"
													onClick={() => setCurrentPage((prev) => Math.max(1, prev - 1))}
													disabled={currentPage === 1}
													className="px-2 py-1 text-xs bg-gray-100 hover:bg-gray-200 disabled:opacity-50 disabled:cursor-not-allowed rounded">
													Prev
												</button>
												<span className="text-xs text-gray-500">
													Page {currentPage} of {customersData.pagination.totalPages}
												</span>
												<button
													type="button"
													onClick={() => setCurrentPage((prev) => Math.min(customersData.pagination.totalPages, prev + 1))}
													disabled={currentPage === customersData.pagination.totalPages}
													className="px-2 py-1 text-xs bg-gray-100 hover:bg-gray-200 disabled:opacity-50 disabled:cursor-not-allowed rounded">
													Next
												</button>
											</div>
										)}
									</>
								)}
							</SelectContent>
						</Select>
					</div>

					<div>
						<Label className={labelStyle()}>Payment Method*</Label>
						<Select>
							<SelectTrigger className={selectTriggerStyle()}>
								<SelectValue placeholder="Select payment method" />
							</SelectTrigger>
							<SelectContent>
								<SelectItem value="paystack">Paystack</SelectItem>
								<SelectItem value="bank">Bank Transfer</SelectItem>
							</SelectContent>
						</Select>
					</div>
					<CustomInput label="Amount Paid" required />
					<CustomInput label="Payment Date" required />
					<CustomInput label="Generated By" containerClassName="col-span-2" required />
					<div className="col-span-2">
						<Label className={labelStyle()}>Note / Remark</Label>
						<Textarea className={inputStyle} rows={3} />
					</div>

					<DialogFooter className="col-span-2 mt-5">
						<ActionButton fullWidth className="py-3">
							Generate Receipt
						</ActionButton>
					</DialogFooter>
				</form>
			</DialogContent>
		</Dialog>
	);
}
